<br /><br />
<div class="container col-sm-offset-3 col-sm-5">
    <div class="panel panel-warning">
        <div class="panel-heading"><h1><strong><?php echo $this->category[0]['categoryName']; ?></strong></h1></div>
        <div class="panel-body">
<?php
 echo "<table  class='table table-striped'  style='text-align:center;'>";

            for($j = 0; $j<count($this->forums); $j++){
                    echo "<tr><td><a href=".$this->baseUrl()."/Forum/listoneforum/forum_id/".$this->forums[$j]['forumID']."><font size='3'>". $this->forums[$j]['forumName']."</font></a></td>";
                 }   
             
         echo "</tr></table><br>"; 

?>
</div>
    </div>
      </div>