<div class="container  col-sm-8 col-sm-offset-2">
    <div class="panel panel-warning">
        <div class="panel-heading"><h1><strong>All Categories</strong></h1></div>
        <div class="panel-body">
<?php
echo "<center><a class='btn btn-primary' href=".$this->baseUrl()."/Category/add/>Add New Category</a></center><br>";
echo "<table class='table table-responsive table-striped'>";
echo "<tr><th>Category Name </th><th>Actions</th></tr>";
for($i = 0; $i<count($this->categories); $i++){
    echo "<tr><td>". $this->categories[$i]['categoryName']."</td>";  
    echo "<td><a class='btn btn-info' href=".$this->baseUrl()."/Category/edit/cat_id/".$this->categories[$i]['categoryID'].">Edit</a> &nbsp;";
    echo "<a class='btn btn-danger' href=".$this->baseUrl()."/Category/delete/cat_id/".$this->categories[$i]['categoryID'].">Delete</a></td></tr>";
}
echo "</table>";
?>
        </div></div>
</div>