<div class="container">
    <div class="panel panel-warning">
        <div class="panel-heading"><h1><strong>Add New Forum</strong></h1></div>
        <div class="panel-body">
    <?php
echo $this->form;
?>
        </div>
        </div>
</div>
<script>
    var save = document.getElementById("savebtn");
    var cancel = document.getElementById("cancelbtn");
   // save.setAttribute("class","col-md-5 btn btn-success");
   // cancel.setAttribute("class","col-md-5 btn btn-danger");



</script>