
<?php

$userInfo = Zend_Auth::getInstance()->getStorage()->read();
if ($userInfo->isAdmin==1){
      if ($this->system[0]['isLocked']==0){
        echo "<a class='col-sm-offset-10 btn btn-danger btn-xs ' role='button'  href=".$this->baseUrl()."/forum/systemstatus><font size='5'>Lock System</font></a>";   
          
    }else{
        echo "<a class='col-sm-offset-10 btn btn-danger btn-xs ' role='button'  href=".$this->baseUrl()."/forum/systemstatus><font size='5'>Unlock System</font></a>"; 
    }    
        
}

?>
<br/><br>
<div class="container  col-sm-10 col-sm-offset-1">
    <div class="panel panel-warning">
        <div class="panel-heading"><h1><strong>New Feeds</strong></h1></div>
        <div class="panel-body">
<?php
for($i = 0; $i<count($this->categories); $i++){
    echo "  <div class='panel panel-danger'> <div class='panel-body'>" ;
            echo "<table class='table table-responsive'>";
            echo "<tr><td  colspan='2'><a class='btn btn-info' href=".$this->baseUrl()."/Category/listonecategory/cat_id/".$this->categories[$i]['categoryID'].">".$this->categories[$i]['categoryName']." category"."</a></td></tr>";  

            for($j = 0; $j<count($this->forums); $j++){
                 if($this->forums[$j]['categoryID']==$this->categories[$i]['categoryID']){
                       echo "<tr><td><a class='success' href=".$this->baseUrl()."/Forum/listoneforum/forum_id/".$this->forums[$j]['forumID'].">". $this->forums[$j]['forumName']." forum"."</a></td>";  
                            for($k=0; $k<count($this->threads); $k++)
                            {
                                if ($this->forums[$j]['forumID']==$this->threads[$k]->forumID)
                                {
                                    for($z = 0; $z<count($this->users); $z++){
                                        if ($this->users[$z]['userID']==$this->threads[$k]->userID){
                                                $name=$this->users[$z]['userName'];
                                                $id=$this->users[$z]['userID'];
                                            }
                                    }
                                    echo "<td><a href=".$this->baseUrl()."/Threads/listonethread/thread_id/".$this->threads[$k]->threadID.">".$this->threads[$k]->threadTitle."</a>&nbsp; &nbsp;".$this->threads[$k]->trreadDate.
                                            "&nbsp; &nbsp; <a  href=".$this->baseUrl()."/user/profileother/userId/".$id.">".$name."</a></td>" ;
                                    
                                }
                            }
                   echo "<tr>";  
                 }   
             }
         echo "</table><br>";    
         echo "</div></div>";
}
?>
        </div></div>
</div>