<?php
echo $this->doctype();
$DOCUMENT_ROOT = $_SERVER['DOCUMENT_ROOT'];
?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>3adalat</title>
    </head>
     <?php
             
        include ( '/var/www/html/3adalat/public/design/header.php');
        echo $this->layout()->content;        
       ?> 
    </html>
    
    