<?php
echo $this->doctype();
$DOCUMENT_ROOT = $_SERVER['DOCUMENT_ROOT'];
?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>3adalat</title>
    </head>

    <?php
    if (!Zend_Auth::getInstance()->hasIdentity()) {             
        include ( '/var/www/html/3adalat/public/design/header.php');
        echo $this->layout()->content;        
        ?>
    </html>
<?php } else {
    $userInfo = Zend_Auth::getInstance()->getStorage()->read();
    if ($userInfo->isAdmin == 0) {
            include ( '/var/www/html/3adalat/public/design/userheader.php');
           
        } elseif ($userInfo->isAdmin==1) {
            include ( '/var/www/html/3adalat/public/design/adminheader.php');
            
        }
        echo $this->layout()->content;

    ?>

<?php }
?>