<script src="<?php echo $this->baseUrl(); ?>/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script type="text/javascript" >
    window.onload = function()
    {
        if(document.getElementById('txtContent')) {
            var oFCKeditor = new FCKeditor('txtContent') ;
            oFCKeditor.BasePath = "<?=$this->baseUrl()?>/js/fckeditor/" ;
            oFCKeditor.Height = 500;
            oFCKeditor.Width = 700;
            oFCKeditor.ReplaceTextarea() ;
        }
    }
</script>

<?php echo $this->form; ?>