   
 <br /><br />
<div class="col-sm-offset-2 col-sm-8"  style=" margin-top:20px;">
<?php

echo "<table border=1 class='table table-striped' style='text-align:center;'>";
echo "<tr><td><b><font size='4'>Thread Title</font></td>"
. "<td><b><font size='4'>Thread Body</font></b></td>"
        . "<td><b><font size='4'>Forum Name</font></b></td>"
        . "<td><b><font size='4'>Action</font></b></td></tr>";
for($i = 0; $i<count($this->threads); $i++){
    
    echo "<tr><td>". $this->threads[$i]['threadTitle']."</td>"; 
    echo "<td>". $this->threads[$i]['threadBody']."</td>";
    
    for($j = 0; $j<count($this->forums); $j++){
            if($this->forums[$j]['forumID']==$this->threads[$i]['forumID']){
                 echo "<td>". $this->forums[$j]['forumName']."</td>"; 
            }
    }
    
    echo "<td><a class='btn btn-success btn-xs' role='button'  href=".$this->baseUrl()."/Threads/edit/id/".$this->threads[$i]['threadID'].">Edit</a>";
    echo " &nbsp;   <a  class='btn btn-warning btn-xs' role='button'  href=".$this->baseUrl()."/Threads/delete/id/".$this->threads[$i]['threadID'].">Delete</a>";
    //
    if($this->threads[$i]['isSticky']==1){
            echo " &nbsp;  <a class='btn btn-primary btn-xs' role='button' href=".$this->baseUrl()."/Threads/status/id/".$this->threads[$i]['threadID']."/status/0/column/isSticky>Sticky</a>";
    }  else {
            echo " &nbsp;   <a class='btn btn-info btn-xs' role='button'  href=".$this->baseUrl()."/Threads/status/id/".$this->threads[$i]['threadID']."/status/1/column/isSticky>UnSticky</a>";

    }
    //
    
     if($this->threads[$i]['isLocked']==1){
            echo " &nbsp;   <a  class='btn btn-danger btn-xs' role='button' href=".$this->baseUrl()."/Threads/status/id/".$this->threads[$i]['threadID']."/status/0/column/isLocked>Locked</a></td></tr>";
    }  else {
            echo " &nbsp;   <a class='btn btn-default btn-xs' role='button' href=".$this->baseUrl()."/Threads/status/id/".$this->threads[$i]['threadID']."/status/1/column/isLocked>Unlocked</a></td></tr>";

    }
    
    
    //
    }
echo "</table>";
?>
</div>   