<body>
    <div class="panel panel-default panel-body col-sm-7 col-sm-offset-2">
<?php
$thread=$this->thread[0];

//get data from session
$userInfo = Zend_Auth::getInstance()->getStorage()->read();
echo "<div>";
echo "<h3 style='color:#8A6D3B;' ><strong>Thread Title :</strong></h3>";
echo "<h4>".$this->thread[0]['threadTitle']."</h4>";
echo "<h3 style='color:#8A6D3B;'><strong>Thread Body :</strong></h3>";
echo "<h4>".$this->thread[0]['threadBody']."</h4>";
echo "<h3 style='color:#8A6D3B;'><strong> Author : </strong></h3>";
 for($z = 0; $z<count($this->users); $z++){
        if ($this->users[$z]['userID']==$this->thread[0]['userID']){
             $name= $this->users[$z]['userName'];
             $id= $this->users[$z]['userID'];
             echo "<h4><a  href=".$this->baseUrl()."/user/profileother/userId/".$id.">".$name."</a></h4>";
         }
  }
echo "<h3 style='color:#8A6D3B;'><strong> Comment : </strong></h3>";
echo "</div>";

if ($userInfo->isAdmin==1){//if he was admin

?>


<textarea rows="5" cols="50" id="reply"></textarea><br/><br/>
<input type="button" class="btn btn-info btn-xs col-sm-offset-2" value="add comment" onclick="addcomment()"></input>
<input type="text" id="thread_id" value=<?php echo $thread['threadID'] ?> hidden>  </input>
<input type="text" id="user" value=<?php echo $userInfo->userID ?> hidden>  </input>
<br/><br/>


<?php
}  else {//normal user
    if ($this->thread[0]['isLocked']==0){ //if it was normal user and thread is not Locked
        
   ?>

       <textarea rows="5" cols="50" id="reply"></textarea><br/><br/>
       <input type="button" class="btn btn-info btn-xs col-sm-offset-2" value="add comment" onclick="addcomment()"></input>
       <input type="text" id="thread_id" value=<?php echo $thread['threadID'] ?> hidden>  </input>
       <input type="text" id="user" value=<?php echo $userInfo->userID ?> hidden>  </input>
       <br/><br/>
       
       
       
<?php
//echo "<div id=".'replies'.">";
        
    }
    
}
?>
 </div>
    <div id="allreply" class="panel panel-warning panel-body col-sm-7 col-sm-offset-2"> 
<?php
//href=".$this->baseUrl()."/replay/delete/id/".$this->reply[$i]['replayID']

                    for($i=0;$i<count($this->reply);$i++){

                    echo "<div style='border:2px solid #8A6D3B;padding:10px;margin-bottom:10px;' id=".$this->reply[$i]['replayID']."co".">";
                     for($z = 0; $z<count($this->users); $z++){
                        if ($this->users[$z]['userID']==$this->reply[$i]['userID']){
                             $name= $this->users[$z]['userName'];
                             $id= $this->users[$z]['userID'];
                             echo "<div><img  style='margin:2px; border:1px solid;' width=40px height=40px src='".$this->baseUrl()."/forum/".$this->users[$z]['photo']."'><sup><font size=2><a  href=".$this->baseUrl()."/user/profileother/userId/".$id.">".$name."</a></font></sup></div>";
                         }
                     }
                   
                    echo "<div id=".$this->reply[$i]['replayID']."rebo".">".$this->reply[$i]['replayBody']."</div>"; 
                    echo "<div style='float:right; margin-top:-20px'>";//body
                    if ($userInfo->isAdmin==1){
                    echo "<input type='button' class='btn btn-success btn-xs' role='button' value='Edit'"."id=".'"'.$this->reply[$i]['replayID'].'e'.'"'." onclick=editrp(".$this->reply[$i]['replayID'].")"."></input>";
                    echo "&nbsp; <input type='button' class='btn btn-warning btn-xs' role='button' value='Delete'"."id=".'"'.$this->reply[$i]['replayID'].'d'.'"'." onclick=delrp(".$this->reply[$i]['replayID'].")"."></input>";
                    }else{
                        if($userInfo->userID==$this->reply[$i]['userID']){
                            echo "<input type='button' class='btn btn-success btn-xs' role='button' value='Edit'"."id=".'"'.$this->reply[$i]['replayID'].'e'.'"'." onclick=editrp(".$this->reply[$i]['replayID'].")"."></input>";
                            echo "&nbsp; <input type='button' class='btn btn-warning btn-xs' role='button' value='Delete'"."id=".'"'.$this->reply[$i]['replayID'].'d'.'"'." onclick=delrp(".$this->reply[$i]['replayID'].")"."></input>";
                                        
                        }
                        
                    }
                    echo "</div>";//buttons
                    echo "</div>";//total
            
        }

?>
    </div>
<script>
    
 function editrp(val){
     document.getElementById(val+"e").setAttribute("disabled","true");
     thecom=document.getElementById(val+"rebo");
     newtextarea=document.createElement("textarea");
     newtextarea.setAttribute("id",val+"area");
     newtextarea.innerHTML=thecom.innerHTML;
     btn=document.createElement("input");
     btn.setAttribute("type","button");
     btn.setAttribute("class","btn btn-info btn-xs");
     btn.setAttribute("value","ok");
     btn.setAttribute("id",val+"btn");
     btn.setAttribute("onclick","aftrok("+val+")");
     thecom.appendChild(newtextarea);
     thecom.appendChild(btn);
 }
 
 function aftrok(val){
     
     if(window.XMLHttpRequest){

            ajaxRequest = new XMLHttpRequest();

    }else{

	ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
    }

    query=val;
    edtcomt=document.getElementById(val+"area").value;
    ajaxRequest.open("GET","../../../replay/edit/id/"+query+"/newval/"+edtcomt,true);
    ajaxRequest.send();
    
    


        ajaxRequest.onreadystatechange=function(){
               if(ajaxRequest.readyState==4 && ajaxRequest.status==200){
                   
                  document.getElementById(val+"rebo").innerHTML=edtcomt; 
                  document.getElementById(val+"e").removeAttribute("disabled");
               }}
     
     
     
 }
 function delrp(val){
     
     if(window.XMLHttpRequest){

            ajaxRequest = new XMLHttpRequest();

    }else{

	ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
    }

    query=val;
    ajaxRequest.open("GET","../../../replay/delete/id/"+query,true);
    ajaxRequest.send();
    
    


        ajaxRequest.onreadystatechange=function(){
               if(ajaxRequest.readyState==4 && ajaxRequest.status==200){
                   
                  document.getElementById(val+"co").remove(); 
               }}
     
     
     
     
 }
    
    
    
function addcomment(){
    
    
  var newcomm=document.getElementById("reply");  
  var addnew=document.createElement("div");
  addnew.setAttribute('style', 'border:2px solid #8A6D3B;padding:10px;margin-bottom:10px;');
  //var userdata=document.createElement("div");
  var replaydata=document.createElement("div");
  
  var controls=document.createElement("div");
    replaydata.innerHTML=newcomm.value;
    document.getElementById('allreply').appendChild(addnew);
    
  

   
    var myimg=document.createElement("img");
    var mysrc=document.getElementById('img').src;
    myimg.setAttribute('src',mysrc);
    myimg.setAttribute('height', '40px');
    myimg.setAttribute('width', '40px');
    
    
    var mysup=document.createElement("sup");
    mysup.innerHTML=document.getElementById("name").innerHTML;

    //mysup.appendChild(link);
    addnew.appendChild(myimg);
    addnew.appendChild(mysup);
    addnew.appendChild(replaydata);
    addnew.appendChild(controls);
    if(window.XMLHttpRequest){

            ajaxRequest = new XMLHttpRequest();

    }else{

	ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
    }

    query=newcomm.value;
    ajaxRequest.open("GET","../../../replay/add/q/"+query+"/thread_id/"+document.getElementById("thread_id").value,true);
    ajaxRequest.send();
    
    


        ajaxRequest.onreadystatechange=function(){
//            res=ajaxRequest.responseText;
//                       console.log(res);
               if(ajaxRequest.readyState==4 && ajaxRequest.status==200){
                       //console.log("succes");  
                       res=ajaxRequest.responseText;
                       //console.log(res);
                       res=res.split("</nav>\n")[1];
                       console.log(res);
                       res=Number(res);
                       console.log(res);
                       
                       addnew.setAttribute("id",res+"co");
                       replaydata.setAttribute("id",res+"rebo");
                       edtbtn=document.createElement("input");
                       edtbtn.setAttribute("type","button");
                       edtbtn.setAttribute("id",res+'e');
                       edtbtn.setAttribute("class",'btn btn-success btn-xs');
                       edtbtn.setAttribute('role','button');
                       edtbtn.setAttribute('value','Edit');
                       edtbtn.setAttribute('onclick',"editrp("+res+")");
                       controls.appendChild(edtbtn);
                       controls.innerHTML+="&nbsp ";
                       
                       delbtn=document.createElement("input");
                       delbtn.setAttribute("type","button");
                       delbtn.setAttribute("id",res+'d');
                       delbtn.setAttribute("class",'btn btn-warning btn-xs');
                       delbtn.setAttribute('role','button');
                       delbtn.setAttribute('value','Delete');
                       delbtn.setAttribute('onclick',"delrp("+res+")");
                       
                       controls.appendChild(delbtn);
                       controls.setAttribute("style","float:right; margin-top:-20px");

                       
                }
        }
 
 
            newcomm.value="";
 
    }
</script>
</body>