<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src ="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </head>
    <body style="background-image: url('<?php echo $this->baseUrl(); ?>/img/bg.jpg');background-repeat: repeat;">
<div class="container">
    <br><br><br><br><br><br>
<div class="panel panel-warning">
    <div class="panel-body" style="background-color:rgba(68, 157, 68, 0.27) !important;">
    <?php
echo $this->form;
?>
        <a href="<?php echo $this->baseUrl()?>/user/add/"> Sign up </a>
    </div></div>
    
</div>
    </body>
</html>
