<div class="container">
    <div class="panel panel-warning">
        <div class="panel-heading"><h1><strong>Profile Page</strong></h1></div>
        <div class="panel-body">
           <?php                                                                                                                                   
           $userInfo = Zend_Auth::getInstance()->getStorage()->read();
//           var_dump($userInfo);
           echo "<a class='btn btn-info' href='".$this->baseUrl()."/user/edit/userID/".$userInfo->userID."'>Edit</a>";
           
           echo "<div class='col-md-2'><img width='120px' height='120px' class='img img-circle' src='".$this->baseUrl()."/forum/".$this->user[0]['photo']."'> <br /></div>";
           echo "<div class='col-md-8'> <div class='panel panel-warning'> <div class='panel-body'>";
           echo "<table>";
           echo "<tr>"."<td><strong style='color:#8A6D3B;'>User Name: </strong></td><td>&nbsp;".$this->user[0]['userName'] ."</td></tr>";
           echo "<tr>"."<td><strong style='color:#8A6D3B;'>Email Address:</strong></td><td>&nbsp;".$this->user[0]['userEmail'] ."</td></tr>";
           echo "<tr>"."<td><strong style='color:#8A6D3B;'>Gender:</strong></td><td>&nbsp;".$this->user[0]['gender'] ."</td></tr>";
           echo "<tr>"."<td><strong style='color:#8A6D3B;'>Country:</strong></td><td>&nbsp;".$this->user[0]['country'] ."</td></tr>";
           echo "</table>";
           echo "</div></div></div>";
           
           
           
           ?> 
            
            
            
            
            
            
            
        </div>
    </div>
</div>
