<div class="container">
    <div class="panel panel-warning">
        <div class="panel-heading"><h1><strong>Profile Page</strong></h1></div>
        <div class="panel-body">
           <?php
           //var_dump($this->user);
           echo "<div class='col-md-3'><img class='img img-thumbnail' src='".$this->user[0]['photo']."'> <br /></div>";
           echo "<div class='col-md-6'> <div class='panel panel-success'> <div class='panel-body'>";
           echo "User Name: "."<p>".$this->user[0]['userName'] ."</p>";
           echo "Email Address: "."<p>".$this->user[0]['userEmail'] ."</p>";
           echo "Gender: "."<p>".$this->user[0]['gender'] ."</p>";
           echo "Country: "."<p>".$this->user[0]['country'] ."</p>";
           echo "</div></div></div>";
           //echo "<img src='".$this->user[0]['photo']."'>";
           
           
           ?> 
            
            
            
            
            
            
            
        </div>
    </div>
</div>